#!/usr/bin/env bash
# answer file for ex3
sudo apt update
sudo apt install -y nginx
# redirect
sudo sed -i '/^\tserver_name.*/a \\n\trewrite ^\/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# html response
echo "Hello World" | tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
