#!/usr/bin/env bash
# answer file for ex4
sudo apt update
sudo apt install -y nginx
# redirect
sudo sed -i '/^\tserver_name.*/a \\n\trewrite ^\/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo -e "Ceci n'est pas une page\n\n" | sudo tee /var/www/html/la_404.html
sudo service nginx restart
