#!/usr/bin/env bash
# displays Best School 10 times, except at line 4 and 8
i=0
while [ "$i" -lt 10 ]; do
	if [ "$i" -eq 4 ]; then
		printf "bad luck\n"
	elif [ "$i" -eq 7 ]; then
		printf "good luck\n"
	else
		printf "Best School\n"
	fi
	((i++))
done
